[file]
max_image_size=33_554_432   # 32 MB
image_download_buffer_size=65_536
image_bucket='image_bucket'

[automations]
new_data_lookback_threshold=7   # 1 week
model_swap_poll_interval=86_400

[database]
database_write_interval=10
lock_contention_timeout=10
database_write_batch_size=20
database_filepath='test.db'

[models]
classifier_h5_filename='classifier.h5'